[package]
name = "chip8_rust"
version = "0.1.0"
authors = ["Kevin Adari <kevin.adari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
sdl2 = "0.34.3"
